const MenuConfig  = [
    {
        title:'文章管理中心',
        key:'/admin/layout/articles',
        children:[
            {
                title:'文章列表',
                key:'/admin/layout/articles/articlesList'
            },
            {
                title:'文章审核',
                key:'/admin/layout/articles/articleCheck'
            },
            {
                title:'置顶管理',
                key:'/admin/layout/articles/articlesIsTop'
            }
        ]
    },
    {
        title:'社区审核',
        key:'/admin/layout/communityCheck',
        children:[
            {
                title:'问题审核（先）',
                key:'/admin/layout/communityCheck/questioncheckBefore'
            },
            {
                title:'问题审核（后）',
                key:'/admin/layout/communityCheck/questioncheckAfter'
            },
            {
                title:'回答审核',
                key:'/admin/layout/communityCheck/answerCheck'
            },
            {
                title:'评论审核',
                key:'/admin/layout/communityCheck/commentCheck'
            }
        ]
    },
    {
        title:'社区列表',
        key:'/admin/layout/communityList',
        children:[
            {
                title:'问题列表',
                key:'/admin/layout/communityList/questionall'
            },
            {
                title:'回答列表',
                key:'/admin/layout/communityList/answerall'
            },
            {
                title:'评论列表',
                key:'/admin/layout/communityList/commentall'
            }
        ]
    },
    {
        title:'经纪人管理中心',
        key:'/admin/layout/agentList',
        children:[
            {
                title:'经纪人审核',
                key:'/admin/layout/agentList/agentCheck'
            },
            {
                title:'经纪人列表',
                key:'/admin/layout/agentList/agentAll'
            },
            {
                title:'经纪人置顶',
                key:'/admin/layout/agentList/agentIsTop'
            }
        ]
    },
    {
        title:'用户管理中心',
        key:'/admin/layout/visitorList',
        children:[
            {
                title:'用户列表',
                key:'/admin/layout/visitorList/visitorAll'
            }
        ]
    },
    {
        title:'系统设置',
        key:'/admin/layout/systemList',
        children:[
            {
                title:'栏目管理',
                key:'/admin/layout/systemList/columnSet'
            },
            {
                title:'banner管理',
                key:'/admin/layout/systemList/bannerSet'
            },
            {
                title:'cdn与apk管理',
                key:'/admin/layout/systemList/cdnandapk'
            }
        ]
    }
]
export default MenuConfig